finalize rename_master_to_main

diff --git a/snowblocks/scripts/rename_master_to_main b/snowblocks/scripts/rename_master_to_main
--- a/snowblocks/scripts/rename_master_to_main
+++ b/snowblocks/scripts/rename_master_to_main
@@ -23,15 +23,97 @@ function echoWarning {
   echo $'\033[0m'
 }
 
-echoStep "Renaming local master branch -> main"
-git branch -m master main
+function ensureBrew {
+  echoStep "Ensuring $1 brew is installed and up to date..."
 
-echoStep "copy origin/master -> origin/main"
+  # Brew's exit code is not consistent when we need to upgrade, so
+  # we need to check the output.
+  set +e
+  OUTPUT=$(brew install $1 2>&1)
+  set -e
+
+  if [[ $OUTPUT =~ To\ upgrade ]]; then
+    brew upgrade $1
+  fi
+}
+
+echoStep "installing dependencies"
+  ensureBrew jq
+  ensureBrew hub
+echoDone
+
+echo ""
 read -s -k '?Press any key to continue.'
-git push origin :master main
+echo ""
+echo ""
 
-echoStep "Delete origin/master"
-echoWarning "NOTE: Please change the default branch before continuing"
-read -s -k '?Press any key to continue .'
-git push origin --delete master
+echoStep "RENAME local master -> main"
+
+master_branch=$(git branch -l master)
+if [[ -z "${master_branch// }" ]]; then 
+ echo "- master branch present ? [NO]"
+ echoWarning "Master branch not present in this repository, exiting.. "
+ exit 1
+else 
+ echo "- master branch present ? [YES]"
+fi
+
+main_branch=$(git branch -l main)
+if [[ -z "${main_branch// }" ]]; then 
+ echo "- main branch present ? [NO]"
+ git branch -m master main
+else 
+ echo "- main branch present ? [YES]"
+fi
+echoDone
+
+echo ""
+read -s -k '?Press any key to continue.'
+echo ""
+echo ""
+
+echoStep "COPY remote:master -> remote:main"
+remote_master_branch=$(git ls-remote --heads git@github.com:$1.git master)
+if [[ -z "${remote_master_branch// }" ]]; then
+  echo "- remote master branch present ? [NO]"
+  git push origin main -u
+else
+  echo "- remote master branch present ? [YES]"
+  git push origin :master main
+fi
+echoDone
+
+echo ""
+read -s -k '?Press any key to continue.'
+echo ""
+echo ""
+
+echoStep "[STEP 3] CHANGE default branch -> main"
+ main_default_branch=$(hub api repos/$1 | jq '.default_branch == "main"')
+ 
+ if [[ "$main_default_branch" == "true" ]]; then
+   echo "3.1 current default_branch = main? [YES]"
+ else
+   echo "3.1 default_branch is set to main? [NO]"
+
+   hub api repos/$1 -X PATCH -F default_branch=main &> /dev/null
+   new_default_branch=$(hub api repos/$1 | jq '.default_branch == "main"')
+   if [[ "$new_default_branch" == "true" ]]; then
+     echo "3.2 default_branch changed to main? [YES]"
+   else
+     echo "3.2 default_branch changed to main? [NO]"
+     echoWarning "Something went wrong changing the default branch, please complete this step manually"
+     read -s -k '?Press any key to continue .'
+   fi
+ fi
+
+echoStep "[STEP 3] DELETE remote master"
+
+remote_master_branch=$(git ls-remote --heads git@github.com:$1.git master)
+if [[ -z "${remote_master_branch// }" ]]; then
+  echo "- remote master branch present ? [NO]"
+else
+  echo "- remote master branch present ? [YES]"
+  git push origin --delete master
+fi
 echoDone
